
version: 0.5.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64

configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml # swig.exe
  - C:\ProgramData\chocolatey\lib -> appveyor.yml # supporting swig Lib files.

install:
  - git submodule update --init
  - IF NOT EXIST C:\ProgramData\chocolatey\bin\swig.exe choco install tools\windows\swig.3.0.12.nupkg --yes --limit-output #> $null
  - git clone https://github.com/X-DataInitiative/tick_appveyor -b master --depth 1 appveyor

build_script:
  # Python 3.6
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; tools/appveyor/run.sh"

artifacts:
  - path: "dist\\*.whl"
    name: Wheels
